version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1s"

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /fonts
  static_dir: static/fonts

- url: /imgs
  static_dir: static/imgs

- url: /js
  static_dir: static/js

- url: /.*
  script: carnes-game.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
